export const LOGIN = "LOGIN";
export const INVALID_LOGIN = "INVALID_LOGIN";
export const LOGOUT = "LOGOUT";
export const UPDATE_START_DATE = "UPDATE_START_DATE";
export const UPDATE_END_DATE = "UPDATE_END_DATE";
export const DISTINCT_CUSTOMERS = "DISTINCT_CUSTOMERS";
